/**
 * Coherence between the reference pages and the pinned OpenSpec CLI.
 * The fixture is generated by `npm run snapshot:openspec` (scripts/openspec-help-snapshot.mjs).
 * Convention: every command documented in a page goes in code formatting (inline or fenced),
 * otherwise it is not extracted and therefore not checked.
 */

export type CliFixture = {
	version: string;
	globalFlags: string[];
	/** Top-level commands ("archive") and subcommands ("change show") with their flags. */
	commands: Record<string, { subcommands: string[]; flags: string[] }>;
	chatCommands: string[];
};

/** One `openspec ...` invocation found in a page. */
export type CliUsage = { command: string | null; subcommand: string | null; flags: string[]; raw: string };

/** Text inside fenced code blocks and inline code spans of a Markdown/MDX source. */
export function codeFragments(source: string): string[] {
	const fragments: string[] = [];
	const withoutFences = source.replace(/^```[^\n]*\n([\s\S]*?)^```/gm, (_match, body: string) => {
		fragments.push(body);
		return '';
	});
	for (const match of withoutFences.matchAll(/`([^`\n]+)`/g)) fragments.push(match[1]);
	return fragments;
}

/** Splits a code line into shell segments and drops trailing comments. */
function segments(line: string): string[] {
	return line
		.replace(/(^|\s)#.*$/, '')
		.split(/&&|\|\||[;|]/)
		.map((s) => s.trim())
		.filter(Boolean);
}

/** `openspec <cmd> [sub] [--flags]` invocations in the code of a page. */
export function extractCliUsages(source: string, fixture: CliFixture): CliUsage[] {
	const usages: CliUsage[] = [];
	for (const fragment of codeFragments(source)) {
		for (const line of fragment.split(/\r?\n/)) {
			for (const segment of segments(line)) {
				const match = segment.match(/(?:^|[\s(])openspec((?:\s+\S+)*)\s*$/);
				if (!match) continue;
				const tokens = match[1].trim().split(/\s+/).filter(Boolean);
				const flags = tokens.filter((t) => /^--?[a-zA-Z]/.test(t)).map((t) => t.split('=')[0]);
				const words = tokens.filter((t) => !t.startsWith('-'));
				// Placeholders such as `<comando>` or `[ruta]` are not commands.
				const command = tokens[0] && /^[a-z]/.test(tokens[0]) ? tokens[0] : null;
				const subs = command ? (fixture.commands[command]?.subcommands ?? []) : [];
				const subcommand = command && words[1] && subs.includes(words[1]) && tokens[1] === words[1] ? words[1] : null;
				usages.push({ command, subcommand, flags, raw: `openspec ${tokens.join(' ')}`.trim() });
			}
		}
	}
	return usages;
}

/** `/opsx:<name>` chat commands in the code of a page. */
export function extractChatCommands(source: string): string[] {
	const found = new Set<string>();
	for (const fragment of codeFragments(source)) {
		for (const match of fragment.matchAll(/\/opsx:[a-z][a-z-]*/g)) found.add(match[0]);
	}
	return [...found];
}

/** `openspecVersion` declared in the frontmatter, if any. */
export function pageVersion(source: string): string | undefined {
	const frontmatter = source.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1] ?? '';
	return frontmatter.match(/^openspecVersion:\s*["']?([^"'\s]+)["']?\s*$/m)?.[1];
}

function versionIssues(source: string, fixture: CliFixture, page: string): string[] {
	const declared = pageVersion(source);
	return declared === fixture.version
		? []
		: [
				`[cli] ${page} declara openspecVersion "${declared ?? '(ausente)'}" pero la fixture es de la versión "${fixture.version}"`,
			];
}

/** Issues of the CLI reference page: unknown commands or flags, or version mismatch. */
export function checkCliPage(source: string, fixture: CliFixture, page = '/referencia/cli/'): string[] {
	const issues = versionIssues(source, fixture, page);
	for (const usage of extractCliUsages(source, fixture)) {
		const { command, subcommand } = usage;
		if (command && !fixture.commands[command]) {
			issues.push(`[cli] ${page} documenta el comando "${command}" (${usage.raw}), que no existe en la fixture`);
			continue;
		}
		const name = subcommand ? `${command} ${subcommand}` : command;
		const allowed = new Set([
			...fixture.globalFlags,
			...(command ? fixture.commands[command].flags : []),
			...(subcommand ? (fixture.commands[`${command} ${subcommand}`]?.flags ?? []) : []),
		]);
		for (const flag of usage.flags) {
			if (!allowed.has(flag)) {
				issues.push(`[cli] ${page} documenta el flag "${flag}" para "${name ?? 'openspec'}", que no existe en la fixture`);
			}
		}
	}
	return issues;
}

/** Issues of the chat commands page: unknown `/opsx:*` commands or version mismatch. */
export function checkChatPage(source: string, fixture: CliFixture, page = '/referencia/comandos-chat/'): string[] {
	const issues = versionIssues(source, fixture, page);
	for (const command of extractChatCommands(source)) {
		if (!fixture.chatCommands.includes(command)) {
			issues.push(`[cli] ${page} documenta el comando de chat "${command}", que no existe en la fixture`);
		}
	}
	return issues;
}

/** Top-level commands of the fixture that a CLI reference must mention (all but `help`). */
export const mainCommands = (fixture: CliFixture): string[] =>
	Object.keys(fixture.commands).filter((name) => !name.includes(' ') && name !== 'help');
