/**
 * Reading order of the printable manual (/manual/). Mirrors the sidebar groups declared in
 * astro.config.mjs: autogenerated groups sort by `sidebar.order` and then by id (as Starlight does);
 * single-slug groups contribute that page. The E2E suite compares the result with the rendered sidebar.
 */
/** `chapter` groups are numbered «Capítulo 01…»; `annex` groups are lettered «Anexo A…». */
export type ManualKind = 'chapter' | 'annex';
export type ManualGroup = { label: string; kind: ManualKind } & ({ directory: string } | { slug: string });

export const MANUAL_GROUPS: readonly ManualGroup[] = [
	{ label: 'Empieza', kind: 'chapter', directory: 'empieza' },
	{ label: 'Guías', kind: 'chapter', directory: 'guias' },
	{ label: 'Con tu agente', kind: 'chapter', directory: 'agentes' },
	{ label: 'En equipo', kind: 'chapter', directory: 'equipo' },
	{ label: 'Referencia', kind: 'annex', directory: 'referencia' },
	{ label: 'Recursos', kind: 'annex', slug: 'recursos' },
	{ label: 'Cómo se hizo', kind: 'annex', slug: 'como-se-hizo' },
];

/** Minimal shape of a `docs` entry the ordering needs. */
export type ManualEntry = {
	id: string;
	data: { title: string; sidebar?: { order?: number; hidden?: boolean } };
};

export type ManualSection<T extends ManualEntry> = {
	group: string;
	kind: ManualKind;
	/** «01», «02»… for chapters; «A», «B»… for annexes. */
	number: string;
	/** «Capítulo 01» or «Anexo A». */
	label: string;
	entry: T;
};

const collator = new Intl.Collator('es-ES');

function inDirectory(id: string, directory: string): boolean {
	return id.startsWith(`${directory}/`);
}

/**
 * Entries linked from the sidebar, in sidebar order. Pages outside every group (landing, 404,
 * legal pages) and pages hidden from the sidebar are left out.
 */
export function orderManualEntries<T extends ManualEntry>(
	entries: readonly T[],
	groups: readonly ManualGroup[] = MANUAL_GROUPS,
): ManualSection<T>[] {
	const sections: ManualSection<T>[] = [];
	let chapters = 0;
	let annexes = 0;
	for (const group of groups) {
		const members =
			'slug' in group
				? entries.filter((e) => e.id === group.slug)
				: entries
						.filter((e) => inDirectory(e.id, group.directory) && !e.data.sidebar?.hidden)
						.sort((a, b) => {
							const ao = a.data.sidebar?.order ?? Number.MAX_VALUE;
							const bo = b.data.sidebar?.order ?? Number.MAX_VALUE;
							return ao !== bo ? ao - bo : collator.compare(a.id, b.id);
						});
		for (const entry of members) {
			const number =
				group.kind === 'chapter'
					? String(++chapters).padStart(2, '0')
					: String.fromCharCode('A'.charCodeAt(0) + annexes++);
			const label = group.kind === 'chapter' ? `Capítulo ${number}` : `Anexo ${number}`;
			sections.push({ group: group.label, kind: group.kind, number, label, entry });
		}
	}
	return sections;
}

/** Fragment id of a manual section: the entry id with slashes turned into hyphens. */
export function manualAnchor(id: string): string {
	return id.replace(/\//g, '-');
}

/** Minimal frontmatter the cover needs. */
export type VersionedEntry = { data: { openspecVersion?: string; lastReviewed?: Date | string } };

/** Highest `openspecVersion` declared by the pages: the site's reference version. */
export function referenceVersion(entries: readonly VersionedEntry[]): string | undefined {
	const parse = (v: string) => v.split('.').map((n) => Number(n));
	return entries
		.map((e) => e.data.openspecVersion)
		.filter((v): v is string => Boolean(v))
		.sort((a, b) => {
			const [pa, pb] = [parse(a), parse(b)];
			for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
				const d = (pa[i] ?? 0) - (pb[i] ?? 0);
				if (d) return d;
			}
			return 0;
		})
		.at(-1);
}

/**
 * «octubre de 2026» from the most recent `lastReviewed`: deterministic, so the manual text
 * (and its fingerprint) only changes when the content does.
 */
export function editionDate(entries: readonly VersionedEntry[]): string | undefined {
	const times = entries
		.map((e) => e.data.lastReviewed)
		.filter((d): d is Date | string => Boolean(d))
		.map((d) => new Date(d).getTime())
		.filter((t) => !Number.isNaN(t));
	if (!times.length) return undefined;
	return new Intl.DateTimeFormat('es-ES', { month: 'long', year: 'numeric', timeZone: 'UTC' }).format(
		new Date(Math.max(...times)),
	);
}
