// @ts-check
import manual from '../data/manual.json' with { type: 'json' };

/** Public path of the downloadable manual (generated by `npm run manual:pdf`). */
export const MANUAL_PDF_PATH = '/manual-openspec.pdf';

/**
 * Formats a byte count as «X,X MB» (es-ES decimals).
 * @param {number} bytes
 */
export function formatPdfSize(bytes) {
	const mb = bytes / (1024 * 1024);
	return `${new Intl.NumberFormat('es-ES', { minimumFractionDigits: 1, maximumFractionDigits: 1 }).format(mb)} MB`;
}

/** Size label of the committed PDF, written by the generation script into src/data/manual.json. */
export const MANUAL_PDF_SIZE = formatPdfSize(manual.bytes);

/** Author shown on the manual cover. */
export const MANUAL_AUTHOR = 'Jesús Pedro Rodríguez';

/**
 * Chapter 00 «Cómo usar este manual»: suggested reading route. Only the manual shows it, because it
 * points at chapters; `slugs` are docs ids, so chapter numbers resolve at build time.
 * @type {readonly { when: string; what: string; slugs: readonly string[] }[]}
 */
export const MANUAL_READING_ROUTE = [
	{ when: 'Día 1', what: 'Entender el modelo mental: specs, changes y deltas.', slugs: ['empieza/que-es', 'empieza/conceptos'] },
	{
		when: 'Día 2',
		what: 'Instalar OpenSpec, ejecutar openspec init en un repositorio de pruebas y completar un primer cambio.',
		slugs: ['empieza/instalacion', 'empieza/primer-cambio'],
	},
	{
		when: 'Día 3',
		what: 'Aprender a escribir specs, recorrer el flujo /opsx y las recetas por tipo de cambio.',
		slugs: ['guias/formato-de-specs', 'guias/flujo-opsx', 'guias/recetas'],
	},
	{
		when: 'Día 4',
		what: 'Redactar config.yaml y las instrucciones del agente para un proyecto real del equipo.',
		slugs: ['guias/brownfield', 'guias/configuracion', 'agentes/claude-code'],
	},
	{ when: 'Día 5', what: 'Primer change real y pequeño: un bugfix o una funcionalidad acotada.', slugs: ['guias/recetas'] },
	{
		when: 'Sprints siguientes',
		what: 'Conectar el backlog y la pipeline y extender el método al equipo.',
		slugs: ['equipo/jira', 'equipo/azure-devops', 'equipo/ci', 'equipo/adopcion'],
	},
];
